### ISSUE TITLE
package version number is lower than LEDE release package

### ISSUE THREAD

**Issue by stangri** [eduperez/mwlwifi_LEDE#13]
Eduardo,

can you please change the package version string so that the version number of your package is higher than that of the release LEDE package? I get the following:
```
WRT3200 in /tmp # opkg install kmod-mwlwifi_4.4.92.10.3.4.0-20171214-0e38a82-9324_arm_cortex-a9_vfpv3.ipk
Not downgrading package kmod-mwlwifi on root from 4.4.92+10.3.4.0.git-2017-06-06-1 to 4.4.92+10.3.4.0-20171214-0e38a82-9324.
```

While I can force downgrade with opkg on a live router, I'm not sure that your package will be picked up over LEDE release package by the Image Builder. If you include the missing ```.git``` after the driver version number in the package version string the problem should go away.

Thanks!

**Comment by eduperez** [comment]
Yes, this was bothering me also, plus there are people who does not know about the force option; however, I have still not found a good solution for this...

The naming schema for LEDE is:
`4.4.92+10.3.4.0.git-2017-06-06-1`

And my naming schema is:
`4.4.92+10.3.4.0-20171214-0e38a82-9324`

The date at the LEDE's schema (`2017-06-06`) is the date of the commit at the repo, so they use `10.3.4.0` as the driver version. But at kaloz's repo (see https://github.com/kaloz/mwlwifi/commit/843d00cd9c134629b9dad7162831ec5f136399b3 for example), the version has also a date: `10.3.4.0-20171214`.  Thus, in my opinion, LEDE is doing it wrong, because they are not using the full version scheme from the upstream repo.

Then there is the problem of using the date from the commit: what happens if there are several commits on the same day? How do you know which of then gets to the package? This is probably not a problem for LEDE, as they are very stable, and just update their package once in a while. But I could need to make one release for each commit, even if there are several commits on the same day. That is why I use the commit identifier instead.

And finally, as the commit identifiers do not follow a sequence, even when updating from one of my packages to the next one, sometimes the force parameter is needed.

At the end, I decided that my packages are intended to be used mostly by advanced users, that want to try some specific version and help debug the drivers, not as a drop-and-forget replacement for the LEDE packages. Having to follow my repo or my posts, and having to force the upgrade, is the small price to pay.

**Comment by stangri** [comment]
I believe that if you just add ```.git``` after the driver version, without any other changes to the naming convention (but ideally inserting dashes between the year/month/date to mimic LEDE), that should resolve the issue. I have nothing against the commit stamp in the version string.

**Comment by eduperez** [comment]
No, I cannot add "`.git`" after the driver version, because the real driver version is "`10.3.4.0-20171214`" (instead of just "`10.3.4.0`", as LEDE does); so it will end as "`4.4.92+10.3.4.0-20171214.git-2017-06-06-0e38a82-9324`", and that will still confuse OPKG.

**Comment by ghost** [comment]
I can also confirm this behavior as I now also build my own mwlwifi drivers
for LEDE snapshots I build myself, the driver strings are very hard to
manipulate.

I personally before building my own drivers bundled within my own built
LEDE snapshots image just uninstalled the mwlwifi driver over Wi-Fi and
reinstalled (the same can be accomplished using the force command).

Uninstalling the driver doesn't cause Wi-Fi to stop working until you
reboot the router.

**Comment by stangri** [comment]
@eduperez thank you for explanation. I'm still missing a piece of information on how you package the ipk. Are you using this makefile: https://github.com/openwrt/openwrt/blob/master/package/kernel/mwlwifi/Makefile? If so, you can just change the ```PKG_VERSION:=``` in line 11 to be similar formatting as this makefile for 17.01 tree (https://github.com/openwrt/openwrt/blob/lede-17.01/package/kernel/mwlwifi/Makefile) + the commit hash.

@rs-se installing on live router is a non-issue. You don't really need to uninstall the old driver either, you can force downgrade with ```opkg install --force-downgrade mwlwifi.ipk```. The problem is that I want to include the newer driver in the image built by Image Builder and it doesn't get picked up because it's considered an older version.

**Comment by eduperez** [comment]
@stangri I am using the makefile at https://git.openwrt.org/openwrt/openwrt.git, and modify it each time, so it points to a specific commit in kaloz's repo. But I do not want to change it to the format used by LEDE, because that format is wrong.

**Comment by johnnyslee** [comment]
> The date at the LEDE's schema (2017-06-06) is the date of the commit at the repo

That's not true, because the date in Makefile:PKG_VERSION seems to match the date in hif/pcie/dev.h:PCIE_DRV_VERSION on the upstream revision indicated by Makefile:PKG_SOURCE_VERSION.
I modified your ipk's control.tar.gz/control:Version to 4.4.92+10.3.4.0.git-2018-01-18-4 and then repacked. The package was installed fine without force downgrade with no error or warning at all.
The number 4 after the date in the version means 4 commits since driver version changed (a149180f..2b99e150). The part after + sign can be generated with https://gist.github.com/johnnyslee/5190efca546c2c22fa95a90c980aa144

**Comment by eduperez** [comment]
@johnnyslee Please, have a look at https://github.com/lede-project/source/commits/master/package/kernel/mwlwifi/Makefile, and notice:

- LEDE has now changed their naming schema, and use the full version, just as I do; for example, current PKG_VERSION is "10.3.4.0-20171214".
- Some package names ("10.3.4.0.git-2017-05-26", for example) do not match any version at kaloz's repo (10.3.4.0 jumped from 20170512 to 20170606); but it's ID matches the commit at that day.

**Comment by eduperez** [comment]
My intention with these packages is not to serve as a "drop and forget" replacement for the official LEDE packages; I publish the updates at the "for developers" forum because I am targeting them to developers and people trying to test new versions.

Sometimes, the same driver version is available with several firmware versions, or some versions may be experimental and not suited for the general user, and some versions (shame on me) may brick your device. I expect users to make an informed decision before upgrading, not just always upgrade blindly to the latest version.

Not being easy to install is a feature, not a bug!
